using Genbox.Wikipedia.Internal;

namespace Genbox.Wikipedia.Enums;

[Flags]
public enum WikiProperty : uint
{
    NotSet = 0,

    /// <summary>Adds the size of the page in bytes.</summary>
    [StringValue("size")] Size = 1 << 0,

    /// <summary>Adds the word count of the page.</summary>
    [StringValue("wordcount")] WordCount = 1 << 1,

    /// <summary>Adds the timestamp of when the page was last edited.</summary>
    [StringValue("timestamp")] Timestamp = 1 << 2,

    /// <summary>Adds a parsed snippet of the page.</summary>
    [StringValue("snippet")] Snippet = 1 << 3,

    /// <summary>Adds a parsed snippet of the page title.</summary>
    [StringValue("titlesnippet")] TitleSnippet = 1 << 4,

    /// <summary>Adds the title of the matching redirect.</summary>
    [StringValue("redirecttitle")] RedirectTitle = 1 << 5,

    /// <summary>Adds a parsed snippet of the redirect title.</summary>
    [StringValue("redirectsnippet")] RedirectSnippet = 1 << 6,

    /// <summary>Adds the title of the matching section.</summary>
    [StringValue("sectiontitle")] SectionTitle = 1 << 7,

    /// <summary>Adds a parsed snippet of the matching section title.</summary>
    [StringValue("sectionsnippet")] SectionSnippet = 1 << 8,

    /// <summary>Adds a boolean indicating if the search matched file content.</summary>
    [StringValue("isfilematch")] IsFileMatch = 1 << 9,

    /// <summary>Adds a parsed snippet of the matching category.</summary>
    [StringValue("categorysnippet")] CategorySnippet = 1 << 10,

    /// <summary>Adds extra data generated by extensions.</summary>
    [StringValue("extensiondata")] ExtensionData = 1 << 11,

    /// <summary>
    /// Include all properties
    /// </summary>
    All = uint.MaxValue
}